import { Inter } from "next/font/google";
import "./globals.css";
import BaseLayout from "@/layouts/BaseLayout";


const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <BaseLayout child={children}/>
        
      </body>
    </html>
  );
}
